### ISSUE TITLE
update React/Redux usage

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#726]
### Is your feature request related to a problem? Please describe.

OED has been transitioning to use React hooks. The following pages already use them:

- Unit pages: src/client/app/components/units/ on several pages
- Conversion pages: src/client/app/components/conversions/ on several pages
- Meter pages: src/client/app/components/meters/ on several pages
- Group pages: src/client/app/components/groups/ on several pages
- User pages: src/client/app/components/admin/users/* but they do not deal with state
- Rate menu: src/client/app/components/GraphicRateMenuComponent.tsx
- Export page: src/client/app/components/ExportComponent.tsx
- Menus for graphic data choices: src/client/app/components/ChartDataSelectComponent.tsx
- Map menu (seems done): src/client/app/components/MapChartSelectComponent.tsx

There are other pages that are already being done or planned as part of other work:

- Page choices: src/client/app/components/HeaderButtonsComponent.tsx
- Options on left side of page: src/client/app/components/MultiSelectComponent.tsx, src/client/app/components/groups/DatasourceBoxComponent & Container, src/client/app/components/ChartLinkComponent.tsx & Container, src/client/app/components/LanguageSelectorComponent.tsx & Container, src/client/app/components/UIOptionsComponent.tsx & Container

The items remaining are:

- [x] admin preferences page (issue #886)
- [x] admin CSV upload pages (issue #887)
- [x] line, bar, compare & map graphics pages (issue #888)
- [x] tooltips (issue #889)
- [x] admin user pages (issue #890)
- [x] admin map viewing page (issue #891)
- [x] chart link (issue #892)
- [x] main containers (dashboard, footer, header, route) (issue #893)
- [x] login (issue #894)
- [x] unsaved warning but wonder if that will go away after all pages work with modal (issue awaiting decision)

There should be linked items for each of the needed items but this issue tracks the overall situation and each item should be checked off as the needed code is merged into OED.

## Brief introduction to what needs to be done

When code is transitioned to React hooks, the following can occur:

- The component/container pair has the container eliminated. The component is converted to a function if it was a class.
- The state accessed from the container and passed as props to the component is now accessed via selectState and useState.
- State updates are done via the set function returned by useState.
- useEffect is used, as needed, to cause updates to state/variables needed for rendering.

There are a number of web sources of information on doing this conversion which may be helpful.

### Describe alternatives you've considered

The conversion has already begun so it should just continue. No real alternatives.

**Comment by huss** [comment]
As of PR #788, the following have been updated to use React hooks:

- dropdown menus for graphing
- meter admin page
- unit admin page
- conversion admin page

**Comment by huss** [comment]
See .eslintrc.json where there are a couple of TODO items that would be addressed once all the containers are removed.

**Comment by huss** [comment]
All these items are either done or migrated to new issues. Thus, this issue is being closed.
